---
title: "Multilevel Regression Modelling with library(lme4)"
author: Leon Kim
date: January 1, 2015
output: slidy_presentation
---


# Reproducible Simulation

```{r}
library(igraph)

par(mar = c(0, 0, 0, 0), oma=c(0,0,0,0), mfrow = c(1, 2)) 
# Nested model, single obs, classification diagram
names <- c("MAJOR","STUDENT","MEASUREMENT OBS")
M <- matrix(data = 0, nrow=3, ncol=3, dimnames = list(names, names))
M[3,2] <- 1; M[2,1] <- 1
M <- graph.adjacency(M, mode="directed",diag=FALSE)
V(M)$size <- c(80,100,200)
node_pos <- matrix(data=c(1,1,1,3,2,1), nrow=3, ncol=2, byrow=FALSE)
plot(M, layout=node_pos, vertex.shape = "crectangle", vertex.size2=50)

# Nested model, signle obs, unit diagram
names <- c("MATH", "STAT","CS", paste0("S_",as.character(seq(1,5)),sep=""), rep("",5))
M <- matrix(data = 0, nrow = 13, ncol = 13, byrow = TRUE, dimnames=list(names,names))
M[4:5,1] <- 1; M[6:7,2] <- 1; M[8,3] <- 1
M <- graph.adjacency(M, mode="directed",diag=FALSE)
V(M)$size <- c(60, 60, 20, rep(40, 5), rep(0,5))
node_pos <- matrix(c( (1+2)/2,3, (3+4)/2,3, 5,3, 
                     1,2, 2,2, 3,2, 4,2, 5,2,
                     1,1.9, 2,1.9, 3,1.9, 4,1.9, 5,1.9), byrow=TRUE, ncol=2)
plot.igraph(M, layout = node_pos, vertex.shape="rectangle")
```

## Reproducibility 

* Same script
* Same results
* Anywhere
    + Single thread
    + Multi-core
    + Cloud Scale

## Everything starts with a seed.
Simulation is based off Pseudo-random number generation (PRNG).

* PRNG is sequential, next number depends on the last state.
* Seeds are used to store the state of a random number generator
* by 'Setting a seed' one can place a PRNG into any exact state.

## Parallel Random Number Generation
Simulation is complicated in new parallel environments.
 
* PRNG is sequential,
* parallel execution is not,
* and order of execution is not guaranteed.

This is where parallel pseudo-random number generators help out.

## Parallel PRNG
Parallel pseudo-random number generators start with a singe state that
can spawn additional streams as well as streams of random numbers.

1. SPRNG
2. L'Ecuyer combined multiple-recursive generator

# Introducing `harvestr`

## R package `harvestr`
<https://github.com/halpo/harvestr>

What `harvestr` does:

* Reproducibility
* Caching
* Under parallelized environments.

------

\titlepage

